# Text Generation with Neural Networks

## Functions for Processing Text

### Reading in files as a string text

In [2]:
def read_file(filepath):
    
    with open(filepath) as f:
        str_text = f.read()
    
    return str_text

In [3]:
read_file('/kaggle/input/sample-text-from-melville-moby-dick/moby_dick_four_chapters.txt')

'Call me Ishmael.  Some years ago--never mind how long\nprecisely--having little or no money in my purse, and nothing\nparticular to interest me on shore, I thought I would sail about a\nlittle and see the watery part of the world.  It is a way I have of\ndriving off the spleen and regulating the circulation.  Whenever I\nfind myself growing grim about the mouth; whenever it is a damp,\ndrizzly November in my soul; whenever I find myself involuntarily\npausing before coffin warehouses, and bringing up the rear of every\nfuneral I meet; and especially whenever my hypos get such an upper\nhand of me, that it requires a strong moral principle to prevent me\nfrom deliberately stepping into the street, and methodically knocking\npeople\'s hats off--then, I account it high time to get to sea as soon\nas I can.  This is my substitute for pistol and ball.  With a\nphilosophical flourish Cato throws himself upon his sword; I quietly\ntake to the ship.  There is nothing surprising in this.  If t

### Tokenize and Clean Text

In [4]:
import spacy
nlp = spacy.load('en_core_web_sm',disable=['parser', 'tagger','ner'])

nlp.max_length = 1198623

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [5]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [6]:
d = read_file('/kaggle/input/sample-text-from-melville-moby-dick/melville-moby_dick.txt')
tokens = separate_punc(d)

/opt/conda/lib/python3.10/site-packages/spacy/pipeline/lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)


In [7]:
tokens

['chapter',
 '1',
 'loomings',
 'call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore',
 'i',
 'thought',
 'i',
 'would',
 'sail',
 'about',
 'a',
 'little',
 'and',
 'see',
 'the',
 'watery',
 'part',
 'of',
 'the',
 'world',
 'it',
 'is',
 'a',
 'way',
 'i',
 'have',
 'of',
 'driving',
 'off',
 'the',
 'spleen',
 'and',
 'regulating',
 'the',
 'circulation',
 'whenever',
 'i',
 'find',
 'myself',
 'growing',
 'grim',
 'about',
 'the',
 'mouth',
 'whenever',
 'it',
 'is',
 'a',
 'damp',
 'drizzly',
 'november',
 'in',
 'my',
 'soul',
 'whenever',
 'i',
 'find',
 'myself',
 'involuntarily',
 'pausing',
 'before',
 'coffin',
 'warehouses',
 'and',
 'bringing',
 'up',
 'the',
 'rear',
 'of',
 'every',
 'funeral',
 'i',
 'meet',
 'and',
 'especially',
 'whenever',
 'my',
 'hypos',
 'get',
 'such

In [8]:
len(tokens)

214708

In [9]:
4431/25

177.24

## Create Sequences of Tokens

In [10]:
# organize into sequences of tokens
train_len = 25+1 # 50 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(tokens)):
    
    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]
    
    # Add to list of sequences
    text_sequences.append(seq)

In [11]:
' '.join(text_sequences[0])

'chapter 1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to'

In [12]:
' '.join(text_sequences[1])

'1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest'

In [13]:
' '.join(text_sequences[2])

'loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me'

In [14]:
len(text_sequences)

214682

# Keras

### Keras Tokenization

In [15]:
from keras.preprocessing.text import Tokenizer

In [16]:
# integer encode sequences of words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [17]:
sequences[0]

[158,
 9443,
 17526,
 402,
 42,
 1043,
 43,
 247,
 659,
 140,
 296,
 116,
 82,
 787,
 347,
 113,
 36,
 50,
 1788,
 6,
 49,
 3028,
 3,
 218,
 442,
 5]

In [18]:
tokenizer.index_word

{1: 'the',
 2: 'of',
 3: 'and',
 4: 'a',
 5: 'to',
 6: 'in',
 7: 'that',
 8: 'his',
 9: 'it',
 10: 'i',
 11: 'he',
 12: 'but',
 13: "'s",
 14: 'as',
 15: 'with',
 16: 'is',
 17: 'was',
 18: 'for',
 19: 'all',
 20: 'this',
 21: 'at',
 22: 'not',
 23: 'by',
 24: 'whale',
 25: 'from',
 26: 'so',
 27: 'him',
 28: 'on',
 29: 'be',
 30: 'one',
 31: 'you',
 32: 'there',
 33: 'now',
 34: 'had',
 35: 'have',
 36: 'or',
 37: 'were',
 38: 'they',
 39: 'like',
 40: 'which',
 41: 'then',
 42: 'me',
 43: 'some',
 44: 'their',
 45: 'what',
 46: 'when',
 47: 'an',
 48: 'are',
 49: 'my',
 50: 'no',
 51: 'upon',
 52: 'out',
 53: 'man',
 54: 'into',
 55: 'ship',
 56: 'up',
 57: 'more',
 58: 'ahab',
 59: 'if',
 60: 'them',
 61: 'old',
 62: 'we',
 63: 'sea',
 64: 'would',
 65: "'",
 66: 'ye',
 67: 'do',
 68: 'other',
 69: 'been',
 70: 'over',
 71: 'these',
 72: 'will',
 73: 'though',
 74: 'only',
 75: 'its',
 76: 'down',
 77: 'such',
 78: 'who',
 79: 'yet',
 80: 'head',
 81: 'time',
 82: 'long',
 83: 'boat

In [19]:
for i in sequences[0]:
    print(f'{i} : {tokenizer.index_word[i]}')

158 : chapter
9443 : 1
17526 : loomings
402 : call
42 : me
1043 : ishmael
43 : some
247 : years
659 : ago
140 : never
296 : mind
116 : how
82 : long
787 : precisely
347 : having
113 : little
36 : or
50 : no
1788 : money
6 : in
49 : my
3028 : purse
3 : and
218 : nothing
442 : particular
5 : to


In [20]:
tokenizer.word_counts

OrderedDict([('chapter', 4447),
             ('1', 28),
             ('loomings', 3),
             ('call', 1382),
             ('me', 16095),
             ('ishmael', 500),
             ('some', 15789),
             ('years', 2400),
             ('ago', 815),
             ('never', 5262),
             ('mind', 2039),
             ('how', 6330),
             ('long', 8567),
             ('precisely', 690),
             ('having', 1679),
             ('little', 6412),
             ('or', 17879),
             ('no', 14916),
             ('money', 305),
             ('in', 105799),
             ('my', 15231),
             ('purse', 178),
             ('and', 164029),
             ('nothing', 2936),
             ('particular', 1273),
             ('to', 117832),
             ('interest', 442),
             ('on', 26910),
             ('shore', 572),
             ('i', 53430),
             ('thought', 3874),
             ('would', 11232),
             ('sail', 2522),
             ('about', 

In [21]:
vocabulary_size = len(tokenizer.word_counts)

### Convert to Numpy Matrix

In [22]:
import numpy as np

In [23]:
sequences = np.array(sequences)

In [24]:
sequences

array([[  158,  9443, 17526, ...,   218,   442,     5],
       [ 9443, 17526,   402, ...,   442,     5,  1165],
       [17526,   402,    42, ...,     5,  1165,    42],
       ...,
       [  240,   938,   351, ...,  1419,  1313,    74],
       [  938,   351,  1418, ...,  1313,    74,   219],
       [  351,  1418,     3, ...,    74,   219,   222]])

# Creating an LSTM based model

In [25]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [26]:
def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))

    model.add(Dense(vocabulary_size, activation='softmax'))
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   
    model.summary()
    
    return model

### Train / Test Split

In [27]:
from keras.utils import to_categorical

In [28]:
sequences

array([[  158,  9443, 17526, ...,   218,   442,     5],
       [ 9443, 17526,   402, ...,   442,     5,  1165],
       [17526,   402,    42, ...,     5,  1165,    42],
       ...,
       [  240,   938,   351, ...,  1419,  1313,    74],
       [  938,   351,  1418, ...,  1313,    74,   219],
       [  351,  1418,     3, ...,    74,   219,   222]])

In [29]:
# First 49 words
sequences[:,:-1]

array([[  158,  9443, 17526, ...,     3,   218,   442],
       [ 9443, 17526,   402, ...,   218,   442,     5],
       [17526,   402,    42, ...,   442,     5,  1165],
       ...,
       [  240,   938,   351, ...,    84,  1419,  1313],
       [  938,   351,  1418, ...,  1419,  1313,    74],
       [  351,  1418,     3, ...,  1313,    74,   219]])

In [30]:
# last Word
sequences[:,-1]

array([   5, 1165,   42, ...,   74,  219,  222])

In [31]:
X = sequences[:115000,:-1]

In [32]:
y = sequences[:115000,-1]

In [33]:
y = to_categorical(y, num_classes=vocabulary_size+1)

In [34]:
seq_len = X.shape[1]

In [35]:
seq_len

25

### Training the Model

In [36]:
# define model
model = create_model(vocabulary_size+1, seq_len)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 25, 25)            438175    
                                                                 
 lstm (LSTM)                 (None, 25, 150)           105600    
                                                                 
 lstm_1 (LSTM)               (None, 150)               180600    
                                                                 
 dense (Dense)               (None, 150)               22650     
                                                                 
 dense_1 (Dense)             (None, 17527)             2646577   
                                                                 
Total params: 3393602 (12.95 MB)
Trainable params: 3393602 (12.95 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


---

----

In [37]:
from pickle import dump,load

In [38]:
# fit model
model.fit(X, y, batch_size=128, epochs=300,verbose=1)

Epoch 1/300
899/899 [==============================] - 65s 59ms/step - loss: 7.0683 - accuracy: 0.0629
Epoch 2/300
899/899 [==============================] - 21s 23ms/step - loss: 6.6307 - accuracy: 0.0765
Epoch 3/300
899/899 [==============================] - 23s 25ms/step - loss: 6.4304 - accuracy: 0.0844
Epoch 4/300
899/899 [==============================] - 21s 23ms/step - loss: 6.2626 - accuracy: 0.0922
Epoch 5/300
899/899 [==============================] - 22s 24ms/step - loss: 6.1489 - accuracy: 0.0981
Epoch 6/300
899/899 [==============================] - 21s 24ms/step - loss: 6.0414 - accuracy: 0.1035
Epoch 7/300
899/899 [==============================] - 20s 23ms/step - loss: 5.9290 - accuracy: 0.1079
Epoch 8/300
899/899 [==============================] - 20s 23ms/step - loss: 5.8229 - accuracy: 0.1121
Epoch 9/300
899/899 [==============================] - 20s 23ms/step - loss: 5.7185 - accuracy: 0.1146
Epoch 10/300
899/899 [==============================] - 21s 23ms/step - l

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



899/899 [==============================] - 20s 23ms/step - loss: 0.6429 - accuracy: 0.8223
Epoch 264/300
899/899 [==============================] - 20s 22ms/step - loss: 0.6012 - accuracy: 0.8343
Epoch 265/300
899/899 [==============================] - 20s 23ms/step - loss: 0.6209 - accuracy: 0.8301
Epoch 266/300
899/899 [==============================] - 20s 23ms/step - loss: 0.6335 - accuracy: 0.8242
Epoch 267/300
899/899 [==============================] - 20s 22ms/step - loss: 0.6116 - accuracy: 0.8321
Epoch 268/300
899/899 [==============================] - 20s 23ms/step - loss: 0.6353 - accuracy: 0.8255
Epoch 269/300
899/899 [==============================] - 20s 22ms/step - loss: 0.6185 - accuracy: 0.8298
Epoch 270/300
899/899 [==============================] - 21s 23ms/step - loss: 0.6122 - accuracy: 0.8306
Epoch 271/300
899/899 [==============================] - 20s 23ms/step - loss: 0.5970 - accuracy: 0.8353
Epoch 272/300
899/899 [==============================] - 20s 23ms/ste

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



899/899 [==============================] - 20s 23ms/step - loss: 0.5642 - accuracy: 0.8428
Epoch 281/300
899/899 [==============================] - 20s 22ms/step - loss: 0.5786 - accuracy: 0.8397
Epoch 282/300
899/899 [==============================] - 20s 22ms/step - loss: 0.5775 - accuracy: 0.8404
Epoch 283/300
899/899 [==============================] - 20s 22ms/step - loss: 0.5706 - accuracy: 0.8413
Epoch 284/300
899/899 [==============================] - 20s 22ms/step - loss: 0.5469 - accuracy: 0.8472
Epoch 285/300
899/899 [==============================] - 20s 22ms/step - loss: 0.5537 - accuracy: 0.8453
Epoch 286/300
899/899 [==============================] - 20s 22ms/step - loss: 0.5809 - accuracy: 0.8373
Epoch 287/300
899/899 [==============================] - 20s 22ms/step - loss: 0.5366 - accuracy: 0.8498
Epoch 288/300
899/899 [==============================] - 20s 22ms/step - loss: 0.5529 - accuracy: 0.8447
Epoch 289/300
899/899 [==============================] - 20s 22ms/ste

In [39]:
# save the model to file
#model.save('epochBIG.h5')
# save the tokenizer
#dump(tokenizer, open('epochBIG', 'wb'))

# Generating New Text

In [40]:
from random import randint
from pickle import load
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences

In [64]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    
    # Final Output
    output_text = []
    
    # Intial Seed Sequence
    input_text = seed_text
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        # Pad sequences to our trained rate (50 words in the video)
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        
        # Predict Class Probabilities for each word
        predictions = model.predict(pad_encoded, verbose=0)
        
        # Grab word
        pred_word_ind = np.argmax(predictions[0])
        pred_word = tokenizer.index_word[pred_word_ind] 
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    # Make it look like a sentence.
    return ' '.join(output_text)

### Grab a random seed sequence

In [65]:
text_sequences[0]

['chapter',
 '1',
 'loomings',
 'call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to']

In [66]:
import random
random.seed(101)
random_pick = random.randint(0,len(text_sequences))

In [67]:
random_seed_text = text_sequences[random_pick]

In [68]:
random_seed_text

['he',
 'recognised',
 'his',
 'cutting',
 'spade',
 'pole',
 'entangled',
 'in',
 'the',
 'lines',
 'that',
 'were',
 'knotted',
 'round',
 'the',
 'tail',
 'of',
 'one',
 'of',
 'these',
 'whales',
 'there',
 "'s",
 'a',
 'pretty',
 'fellow']

In [69]:
seed_text = ' '.join(random_seed_text)

In [70]:
seed_text

"he recognised his cutting spade pole entangled in the lines that were knotted round the tail of one of these whales there 's a pretty fellow"

In [77]:
generated_text = generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=25)
print(generated_text)

's crew now i heard one hundred from all the planks with him to lighten her over a living point of hydrus and the cheerful


### Exploring Generated Sequence

In [78]:
final_text = seed_text + generated_text
print(final_text)

he recognised his cutting spade pole entangled in the lines that were knotted round the tail of one of these whales there 's a pretty fellow's crew now i heard one hundred from all the planks with him to lighten her over a living point of hydrus and the cheerful
